language: php
php:
    - 5.5
    - 5.4
    - hhvm

before_script:
    - wget http://getcomposer.org/composer.phar
    - php composer.phar install --dev --no-interaction

script: 
    - mkdir -p build/logs
    - phpunit --bootstrap test/config.php --coverage-clover build/logs/clover.xml test

after_script:
 - php mosbth/bin/coveralls -v

notifications:
    irc: "irc.freenode.org#dbwebb"
